<div class="widget-product-grid">
	<?php foreach ($block->getEnabledBanners() as $banner) : ?>
        <div>
            <a href="<?= $banner['link'] ? $banner['link'] : 'javascript:void(0)' ?>">
                <?php echo $block->filterOutputHtml($banner['content']);?>
            </a>
        </div>
    <?php endforeach ?>  
</div>

<script>
require([
        'jquery',
        'slick'
    ], function ($) {
        jQuery(document).ready(function () {
            jQuery(".widget-product-grid").slick({
              dots: true,
              infinite: true,
              speed: 300,
              slidesToShow: 1,
              adaptiveHeight: true
            });
        });
    });
</script>